// API = 'https://moneyfrog.in/financial-page-api/' +
//               userID +
//               '/mutual_funds?login_token=' +
//               userToken

// {
// 	"mutual_funds": [{
// 		"mf_id": "54633",
// 		"scheme_id": "4110",
// 		"hash_et": null,
// 		"nse_code": "43NZ",
// 		"mf_type": "Debt",
// 		"amc": "Aditya Birla Sun Life Mutual Fund",
// 		"scheme_name": "Aditya Birla Sun Life Low duration Fund - Growth - Direct Plan",
// 		"scheme_code": "18230",
// 		"asset_type": "Low Duration",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "1042484965",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "404114",
// 		"current_units": "692.076",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "583.9153",
// 		"buy_value": "399980",
// 		"current_unit": "692.076",
// 		"start_date": "28-03-2022",
// 		"SIP_start_Date": "28-03-2022",
// 		"xirr": "3.47",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "B43NZ",
// 		"customeriin": null,
// 		"percentage": "1.03",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54634",
// 		"scheme_id": "4023",
// 		"hash_et": null,
// 		"nse_code": "BDDGGGR",
// 		"mf_type": "Debt",
// 		"amc": "Axis Mutual Fund",
// 		"scheme_name": "Axis Banking & PSU Debt Fund - Direct Plan - Growth Option",
// 		"scheme_code": "18182",
// 		"asset_type": "Banking and PSU",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "91099265431",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "4373",
// 		"current_units": "1.985",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "2202.9232",
// 		"buy_value": "4134",
// 		"current_unit": "1.985",
// 		"start_date": "01-12-2020",
// 		"SIP_start_Date": "01-12-2020",
// 		"xirr": "3.36",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "128BDDGGGR",
// 		"customeriin": null,
// 		"percentage": "5.78",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54663",
// 		"scheme_id": "2597",
// 		"hash_et": null,
// 		"nse_code": "EFGPGGR",
// 		"mf_type": "Equity",
// 		"amc": "Axis Mutual Fund",
// 		"scheme_name": "Axis Bluechip Fund - Regular Plan - Growth",
// 		"scheme_code": "8250",
// 		"asset_type": "Large Cap",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "910109582743 (MFrog)",
// 		"plan": "SIP",
// 		"mode": "Monthly",
// 		"current_value": "1979",
// 		"current_units": "49.497",
// 		"brought_thru": "Moneyfrog",
// 		"nav": "39.98",
// 		"buy_value": "2000",
// 		"current_unit": "49.497",
// 		"start_date": null,
// 		"SIP_start_Date": null,
// 		"xirr": "-14.87",
// 		"source": "Moneyfrog",
// 		"buy_sell_status": "1",
// 		"purchase_allowed": "Y",
// 		"plan_type": "REGULAR",
// 		"concat(p.amc_code,product_code)": "102EFGPGGR",
// 		"customeriin": null,
// 		"percentage": "-1.05",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54635",
// 		"scheme_id": "7621",
// 		"hash_et": null,
// 		"nse_code": "SCDGGGR",
// 		"mf_type": "Equity",
// 		"amc": "Axis Mutual Fund",
// 		"scheme_name": "Axis Small Cap Fund - Direct Plan - Growth",
// 		"scheme_code": "24657",
// 		"asset_type": "Small Cap",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "91099265431",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "334437",
// 		"current_units": "5270.863",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "63.45",
// 		"buy_value": "309157",
// 		"current_unit": "5270.863",
// 		"start_date": "12-03-2021",
// 		"SIP_start_Date": "12-03-2021",
// 		"xirr": "11.56",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "128SCDGGGR",
// 		"customeriin": null,
// 		"percentage": "8.18",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54636",
// 		"scheme_id": "60589",
// 		"hash_et": null,
// 		"nse_code": "USDGGGR",
// 		"mf_type": "Debt",
// 		"amc": "Axis Mutual Fund",
// 		"scheme_name": "Axis Ultra Short Term Fund - Direct Plan Growth",
// 		"scheme_code": "41048",
// 		"asset_type": "Ultra Short Duration",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "91099265431",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "19730",
// 		"current_units": "1564.873",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "12.6075",
// 		"buy_value": "19505",
// 		"current_unit": "1564.873",
// 		"start_date": "11-02-2021",
// 		"SIP_start_Date": "11-02-2021",
// 		"xirr": "4.2",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "128USDGGGR",
// 		"customeriin": null,
// 		"percentage": "1.15",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54637",
// 		"scheme_id": "4225",
// 		"hash_et": null,
// 		"nse_code": "",
// 		"mf_type": "Debt",
// 		"amc": "BNP Paribas Mutual Fund",
// 		"scheme_name": "BNP Paribas Corporate Bond Fund - Direct Plan - Growth Option",
// 		"scheme_code": "18307",
// 		"asset_type": "Corporate Bond",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "3102326112",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "395375",
// 		"current_units": "17026.584",
// 		"brought_thru": "000000-0",
// 		"nav": "23.221",
// 		"buy_value": "399980",
// 		"current_unit": "17026.584",
// 		"start_date": "28-03-2022",
// 		"SIP_start_Date": "28-03-2022",
// 		"xirr": "-3.77",
// 		"source": "000000-0",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": null,
// 		"plan_type": null,
// 		"concat(p.amc_code,product_code)": null,
// 		"customeriin": null,
// 		"percentage": "-1.15",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54638",
// 		"scheme_id": "2829",
// 		"hash_et": null,
// 		"nse_code": "770",
// 		"mf_type": "Equity",
// 		"amc": "DSP Mutual Fund",
// 		"scheme_name": "DSP Equity Opportunities Fund - Direct Plan - Growth",
// 		"scheme_code": "18416",
// 		"asset_type": "Large & Mid Cap",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "6564632\/14",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "428453",
// 		"current_units": "1207.395",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "354.857",
// 		"buy_value": "415516",
// 		"current_unit": "1207.395",
// 		"start_date": "08-02-2021",
// 		"SIP_start_Date": "08-02-2021",
// 		"xirr": "4.02",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "N",
// 		"plan_type": "REGULAR",
// 		"concat(p.amc_code,product_code)": "K770",
// 		"customeriin": null,
// 		"percentage": "3.11",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54639",
// 		"scheme_id": "23937",
// 		"hash_et": null,
// 		"nse_code": "LISGGGR",
// 		"mf_type": "Debt",
// 		"amc": "DSP Mutual Fund",
// 		"scheme_name": "DSP Low Duration Fund - Direct Plan - Growth",
// 		"scheme_code": "32183",
// 		"asset_type": "Income",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "6564632\/14",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "4503",
// 		"current_units": "271.254",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "16.5986",
// 		"buy_value": "4367",
// 		"current_unit": "271.254",
// 		"start_date": "11-02-2021",
// 		"SIP_start_Date": "11-02-2021",
// 		"xirr": "4.17",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "REGULAR",
// 		"concat(p.amc_code,product_code)": "101LISGGGR",
// 		"customeriin": null,
// 		"percentage": "3.09",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54666",
// 		"scheme_id": "106312",
// 		"hash_et": null,
// 		"nse_code": "104",
// 		"mf_type": "Equity",
// 		"amc": "DSP Mutual Fund",
// 		"scheme_name": "DSP Midcap Fund - Regular Plan - Growth",
// 		"scheme_code": "735",
// 		"asset_type": "Mid Cap",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "6617660\/10 (MFrog)",
// 		"plan": "SIP",
// 		"mode": "Monthly",
// 		"current_value": "1007",
// 		"current_units": "12.42",
// 		"brought_thru": "Moneyfrog",
// 		"nav": "81.044",
// 		"buy_value": "1000",
// 		"current_unit": "12.42",
// 		"start_date": null,
// 		"SIP_start_Date": null,
// 		"xirr": "10.52",
// 		"source": "Moneyfrog",
// 		"buy_sell_status": "1",
// 		"purchase_allowed": "Y",
// 		"plan_type": "REGULAR",
// 		"concat(p.amc_code,product_code)": "D104",
// 		"customeriin": null,
// 		"percentage": "0.70",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54640",
// 		"scheme_id": "4587",
// 		"hash_et": null,
// 		"nse_code": "711",
// 		"mf_type": "Debt",
// 		"amc": "DSP Mutual Fund",
// 		"scheme_name": "DSP Short Term Fund - Direct Plan - Growth",
// 		"scheme_code": "18419",
// 		"asset_type": "Short Duration",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "6564632\/14",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "13539",
// 		"current_units": "333.3",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "40.6194",
// 		"buy_value": "13499",
// 		"current_unit": "333.3",
// 		"start_date": "16-09-2021",
// 		"SIP_start_Date": "16-09-2021",
// 		"xirr": "2.28",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "N",
// 		"plan_type": "REGULAR",
// 		"concat(p.amc_code,product_code)": "K711",
// 		"customeriin": null,
// 		"percentage": "0.29",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54641",
// 		"scheme_id": "2157",
// 		"hash_et": null,
// 		"nse_code": "758",
// 		"mf_type": "Commodity",
// 		"amc": "DSP Mutual Fund",
// 		"scheme_name": "DSP World Gold Fund - Direct Plan - Growth",
// 		"scheme_code": "19442",
// 		"asset_type": "Gold Fund",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "6564632\/14",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "37819",
// 		"current_units": "2734.071",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "13.8323",
// 		"buy_value": "49998",
// 		"current_unit": "2734.071",
// 		"start_date": "12-03-2021",
// 		"SIP_start_Date": "12-03-2021",
// 		"xirr": "-25.16",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "N",
// 		"plan_type": "REGULAR",
// 		"concat(p.amc_code,product_code)": "K758",
// 		"customeriin": null,
// 		"percentage": "-24.36",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54642",
// 		"scheme_id": "3078",
// 		"hash_et": null,
// 		"nse_code": "8042",
// 		"mf_type": "Equity",
// 		"amc": "ICICI Prudential Mutual Fund",
// 		"scheme_name": "ICICI Prudential Bluechip Fund - Direct Plan - Growth",
// 		"scheme_code": "18493",
// 		"asset_type": "Large Cap",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "16819317\/91",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "429372",
// 		"current_units": "6498.739",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "66.07",
// 		"buy_value": "413394",
// 		"current_unit": "6498.739",
// 		"start_date": "08-02-2021",
// 		"SIP_start_Date": "08-02-2021",
// 		"xirr": "4.98",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "P8042",
// 		"customeriin": null,
// 		"percentage": "3.87",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54643",
// 		"scheme_id": "5189",
// 		"hash_et": null,
// 		"nse_code": "8009",
// 		"mf_type": "Debt",
// 		"amc": "ICICI Prudential Mutual Fund",
// 		"scheme_name": "ICICI Prudential Short Term Fund - Direct Plan - Growth Option",
// 		"scheme_code": "18509",
// 		"asset_type": "Short Duration",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "16819317\/91",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "16018",
// 		"current_units": "310.967",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "51.51",
// 		"buy_value": "15868",
// 		"current_unit": "310.967",
// 		"start_date": "16-09-2021",
// 		"SIP_start_Date": "16-09-2021",
// 		"xirr": "2.37",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "P8009",
// 		"customeriin": null,
// 		"percentage": "0.95",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54644",
// 		"scheme_id": "5149",
// 		"hash_et": null,
// 		"nse_code": "8123",
// 		"mf_type": "Debt",
// 		"amc": "ICICI Prudential Mutual Fund",
// 		"scheme_name": "ICICI Prudential Ultra Short Term Fund - Direct Plan - Growth",
// 		"scheme_code": "20010",
// 		"asset_type": "Ultra Short Duration",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "16819317\/91",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "4731",
// 		"current_units": "195.595",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "24.1863",
// 		"buy_value": "4559",
// 		"current_unit": "195.595",
// 		"start_date": "11-02-2021",
// 		"SIP_start_Date": "11-02-2021",
// 		"xirr": "4.64",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "P8123",
// 		"customeriin": null,
// 		"percentage": "3.77",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54645",
// 		"scheme_id": "3278",
// 		"hash_et": null,
// 		"nse_code": "123D",
// 		"mf_type": "Equity",
// 		"amc": "Kotak Mahindra Mutual Fund",
// 		"scheme_name": "Kotak Emerging Equity Scheme - Growth - Direct",
// 		"scheme_code": "19371",
// 		"asset_type": "Mid Cap",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "8040610\/33",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "449978",
// 		"current_units": "5905.289",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "76.199",
// 		"buy_value": "420579",
// 		"current_unit": "5905.289",
// 		"start_date": "08-02-2021",
// 		"SIP_start_Date": "08-02-2021",
// 		"xirr": "9.04",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "K123D",
// 		"customeriin": null,
// 		"percentage": "6.99",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54668",
// 		"scheme_id": "3297",
// 		"hash_et": null,
// 		"nse_code": "168",
// 		"mf_type": "Equity",
// 		"amc": "Kotak Mahindra Mutual Fund",
// 		"scheme_name": "Kotak Flexicap Fund - Growth",
// 		"scheme_code": "7874",
// 		"asset_type": "Multi Cap",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "8177206\/70 (MFrog)",
// 		"plan": "SIP",
// 		"mode": "Monthly",
// 		"current_value": "993",
// 		"current_units": "20.65",
// 		"brought_thru": "Moneyfrog",
// 		"nav": "48.061",
// 		"buy_value": "1000",
// 		"current_unit": "20.65",
// 		"start_date": null,
// 		"SIP_start_Date": null,
// 		"xirr": "-10.83",
// 		"source": "Moneyfrog",
// 		"buy_sell_status": "1",
// 		"purchase_allowed": "N",
// 		"plan_type": "REGULAR",
// 		"concat(p.amc_code,product_code)": "D168",
// 		"customeriin": null,
// 		"percentage": "-0.80",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54646",
// 		"scheme_id": "23483",
// 		"hash_et": null,
// 		"nse_code": "255G",
// 		"mf_type": "Debt",
// 		"amc": "Kotak Mahindra Mutual Fund",
// 		"scheme_name": "Kotak Low Duration Fund- Direct Plan- Growth Option",
// 		"scheme_code": "18783",
// 		"asset_type": "Low Duration",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "8040610\/33",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "15055",
// 		"current_units": "5.157",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "2919.1676",
// 		"buy_value": "14968",
// 		"current_unit": "5.157",
// 		"start_date": "16-09-2021",
// 		"SIP_start_Date": "16-09-2021",
// 		"xirr": "2.87",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "K255G",
// 		"customeriin": null,
// 		"percentage": "0.57",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54647",
// 		"scheme_id": "1931",
// 		"hash_et": null,
// 		"nse_code": "135D",
// 		"mf_type": "Debt",
// 		"amc": "Kotak Mahindra Mutual Fund",
// 		"scheme_name": "Kotak Savings Fund-Growth - Direct",
// 		"scheme_code": "18640",
// 		"asset_type": "Ultra Short Duration",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "8040610\/33",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "4143",
// 		"current_units": "113.726",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "36.4282",
// 		"buy_value": "4006",
// 		"current_unit": "113.726",
// 		"start_date": "11-02-2021",
// 		"SIP_start_Date": "11-02-2021",
// 		"xirr": "3.89",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "K135D",
// 		"customeriin": null,
// 		"percentage": "3.42",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54648",
// 		"scheme_id": "3332",
// 		"hash_et": null,
// 		"nse_code": "17D",
// 		"mf_type": "Equity",
// 		"amc": "L&T Mutual Fund",
// 		"scheme_name": "L&T Mid Cap Fund-Direct Plan-Growth Plan",
// 		"scheme_code": "18693",
// 		"asset_type": "Mid Cap",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "3790811\/41",
// 		"plan": "SIP",
// 		"mode": "Monthly",
// 		"current_value": "342007",
// 		"current_units": "1619.27",
// 		"brought_thru": "DIRECTONLINE",
// 		"nav": "211.21",
// 		"buy_value": "339983",
// 		"current_unit": "1619.27",
// 		"start_date": "28-05-2019",
// 		"SIP_start_Date": "28-05-2019",
// 		"xirr": "18.12",
// 		"source": "DIRECTONLINE",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "K17D",
// 		"customeriin": null,
// 		"percentage": "0.60",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54661",
// 		"scheme_id": "3362",
// 		"hash_et": null,
// 		"nse_code": "EBRGGGR",
// 		"mf_type": "Equity",
// 		"amc": "Mirae Asset Mutual Fund",
// 		"scheme_name": "Mirae Asset Emerging Bluechip Fund - Regular Plan - Growth Option",
// 		"scheme_code": "9767",
// 		"asset_type": "Large & Mid Cap",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "77736818246 (MFrog)",
// 		"plan": "SIP",
// 		"mode": "Monthly",
// 		"current_value": "1992",
// 		"current_units": "22.371",
// 		"brought_thru": "Moneyfrog",
// 		"nav": "89.015",
// 		"buy_value": "2000",
// 		"current_unit": "22.371",
// 		"start_date": null,
// 		"SIP_start_Date": null,
// 		"xirr": "-6.31",
// 		"source": "Moneyfrog",
// 		"buy_sell_status": "1",
// 		"purchase_allowed": "Y",
// 		"plan_type": "REGULAR",
// 		"concat(p.amc_code,product_code)": "103EBRGGGR",
// 		"customeriin": null,
// 		"percentage": "-0.45",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54649",
// 		"scheme_id": "61066",
// 		"hash_et": null,
// 		"nse_code": "",
// 		"mf_type": "Hybrid",
// 		"amc": "Motilal Oswal Mutual Fund",
// 		"scheme_name": "Motilal Oswal Multi Asset Fund - Direct Plan - Growth Option",
// 		"scheme_code": "45018",
// 		"asset_type": "Multi Asset Allocation",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "91020968246",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "875203",
// 		"current_units": "81221.543",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "10.7755",
// 		"buy_value": "848958",
// 		"current_unit": "81221.543",
// 		"start_date": "01-12-2020",
// 		"SIP_start_Date": "01-12-2020",
// 		"xirr": "2.21",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": null,
// 		"plan_type": null,
// 		"concat(p.amc_code,product_code)": null,
// 		"customeriin": null,
// 		"percentage": "3.09",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54650",
// 		"scheme_id": "61039",
// 		"hash_et": null,
// 		"nse_code": "N1GDGGR",
// 		"mf_type": "Equity",
// 		"amc": "Motilal Oswal Mutual Fund",
// 		"scheme_name": "Motilal Oswal Nasdaq 100 Fund of Fund- Direct Plan Growth",
// 		"scheme_code": "41761",
// 		"asset_type": "International",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "91020968246",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "313733",
// 		"current_units": "15989.605",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "19.621",
// 		"buy_value": "344783",
// 		"current_unit": "15989.605",
// 		"start_date": "08-02-2021",
// 		"SIP_start_Date": "08-02-2021",
// 		"xirr": "-7.4",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "N",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "127N1GDGGR",
// 		"customeriin": null,
// 		"percentage": "-9.01",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54651",
// 		"scheme_id": "7263",
// 		"hash_et": null,
// 		"nse_code": "USGDGGR",
// 		"mf_type": "Debt",
// 		"amc": "Motilal Oswal Mutual Fund",
// 		"scheme_name": "Motilal Oswal Ultra Short Term Fund (MOFUSTF) -Direct Plan- Growth",
// 		"scheme_code": "22538",
// 		"asset_type": "Ultra Short Duration",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "91020968246",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "21726",
// 		"current_units": "1495.568",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "14.5263",
// 		"buy_value": "21529",
// 		"current_unit": "1495.568",
// 		"start_date": "11-02-2021",
// 		"SIP_start_Date": "11-02-2021",
// 		"xirr": "3.13",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "127USGDGGR",
// 		"customeriin": null,
// 		"percentage": "0.91",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54652",
// 		"scheme_id": "6155",
// 		"hash_et": null,
// 		"nse_code": "LPIDDR",
// 		"mf_type": "Debt",
// 		"amc": "Nippon India Mutual Fund",
// 		"scheme_name": "Nippon India Low Duration Fund -Daily Dividend Reinvestment Option",
// 		"scheme_code": "2620",
// 		"asset_type": "Low Duration",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "407135659006",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "11",
// 		"current_units": "0.01",
// 		"brought_thru": "ARN-0155",
// 		"nav": "1008.9708",
// 		"buy_value": "0",
// 		"current_unit": "0.01",
// 		"start_date": "01-11-2012",
// 		"SIP_start_Date": "01-11-2012",
// 		"xirr": "0.1",
// 		"source": "ARN-0155",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "REGULAR",
// 		"concat(p.amc_code,product_code)": "RMFLPIDDR",
// 		"customeriin": null,
// 		"percentage": "inf",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54654",
// 		"scheme_id": "7343",
// 		"hash_et": null,
// 		"nse_code": "CPAGGR",
// 		"mf_type": "Debt",
// 		"amc": "Nippon India Mutual Fund",
// 		"scheme_name": "Nippon India Ultra Short Duration Fund- Direct Plan- Growth Option",
// 		"scheme_code": "18857",
// 		"asset_type": "Ultra Short Duration",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "477262603121",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "202664",
// 		"current_units": "56.698",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "3574.4296",
// 		"buy_value": "199990",
// 		"current_unit": "56.698",
// 		"start_date": "28-03-2022",
// 		"SIP_start_Date": "28-03-2022",
// 		"xirr": "4.5",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "RMFCPAGGR",
// 		"customeriin": null,
// 		"percentage": "1.34",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54653",
// 		"scheme_id": "44106",
// 		"hash_et": null,
// 		"nse_code": "UEAGGR",
// 		"mf_type": "Equity",
// 		"amc": "Nippon India Mutual Fund",
// 		"scheme_name": "Nippon India US Equity Opportunites Fund- Direct Plan- Growth Plan- Growth Option",
// 		"scheme_code": "33225",
// 		"asset_type": "International",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "477259370622",
// 		"plan": "One Time Investment",
// 		"mode": "",
// 		"current_value": "8095",
// 		"current_units": "354.179",
// 		"brought_thru": "Mfrog-Direct",
// 		"nav": "22.8556",
// 		"buy_value": "9000",
// 		"current_unit": "354.179",
// 		"start_date": "21-01-2022",
// 		"SIP_start_Date": "21-01-2022",
// 		"xirr": "-19.72",
// 		"source": "Mfrog-Direct",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "RMFUEAGGR",
// 		"customeriin": null,
// 		"percentage": "-10.06",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54655",
// 		"scheme_id": "3736",
// 		"hash_et": null,
// 		"nse_code": "D099G",
// 		"mf_type": "Equity",
// 		"amc": "SBI Mutual Fund",
// 		"scheme_name": "SBI Flexicap Fund - DIRECT PLAN - Growth Option",
// 		"scheme_code": "19018",
// 		"asset_type": "Flexi Cap",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "14121213",
// 		"plan": "SIP",
// 		"mode": "Monthly",
// 		"current_value": "314900",
// 		"current_units": "4156.314",
// 		"brought_thru": "DIRECT",
// 		"nav": "75.7641",
// 		"buy_value": "319984",
// 		"current_unit": "4156.314",
// 		"start_date": "08-11-2019",
// 		"SIP_start_Date": "08-11-2019",
// 		"xirr": "21.85",
// 		"source": "DIRECT",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "LD099G",
// 		"customeriin": null,
// 		"percentage": "-1.59",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54656",
// 		"scheme_id": "3732",
// 		"hash_et": null,
// 		"nse_code": "D091G",
// 		"mf_type": "Equity",
// 		"amc": "SBI Mutual Fund",
// 		"scheme_name": "SBI Magnum MIDCAP FUND - DIRECT PLAN - GROWTH",
// 		"scheme_code": "19008",
// 		"asset_type": "Mid Cap",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "14121213",
// 		"plan": "SIP",
// 		"mode": "Monthly",
// 		"current_value": "365514",
// 		"current_units": "2496.312",
// 		"brought_thru": "DIRECT",
// 		"nav": "146.4214",
// 		"buy_value": "339983",
// 		"current_unit": "2496.312",
// 		"start_date": "07-11-2019",
// 		"SIP_start_Date": "07-11-2019",
// 		"xirr": "36.03",
// 		"source": "DIRECT",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "LD091G",
// 		"customeriin": null,
// 		"percentage": "7.51",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54657",
// 		"scheme_id": "3764",
// 		"hash_et": null,
// 		"nse_code": "D346G",
// 		"mf_type": "Equity",
// 		"amc": "SBI Mutual Fund",
// 		"scheme_name": "SBI Small Cap Fund - Direct Plan - Growth",
// 		"scheme_code": "18390",
// 		"asset_type": "Small Cap",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "14121213",
// 		"plan": "SIP",
// 		"mode": "Monthly",
// 		"current_value": "390897",
// 		"current_units": "3535.849",
// 		"brought_thru": "DIRECT",
// 		"nav": "110.5523",
// 		"buy_value": "368982",
// 		"current_unit": "3535.849",
// 		"start_date": "02-07-2018",
// 		"SIP_start_Date": "02-07-2018",
// 		"xirr": "29.65",
// 		"source": "DIRECT",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "N",
// 		"plan_type": "DIRECT",
// 		"concat(p.amc_code,product_code)": "LD346G",
// 		"customeriin": null,
// 		"percentage": "5.94",
// 		"iin_exists_or_not": "no"
// 	}, {
// 		"mf_id": "54658",
// 		"scheme_id": "3838",
// 		"hash_et": null,
// 		"nse_code": "04",
// 		"mf_type": "Equity",
// 		"amc": "Sundaram Mutual Fund",
// 		"scheme_name": "Sundaram Midcap Fund -Growth",
// 		"scheme_code": "3067",
// 		"asset_type": "Mid Cap",
// 		"holder_name": "Dhole Saurabh",
// 		"folio_no": "501764092189",
// 		"plan": "SIP",
// 		"mode": "Monthly",
// 		"current_value": "236309",
// 		"current_units": "359.067",
// 		"brought_thru": "ARN-41198",
// 		"nav": "658.1174",
// 		"buy_value": "198468",
// 		"current_unit": "359.067",
// 		"start_date": "11-07-2017",
// 		"SIP_start_Date": "11-07-2017",
// 		"xirr": "-4.59",
// 		"source": "ARN-41198",
// 		"buy_sell_status": "0",
// 		"purchase_allowed": "Y",
// 		"plan_type": "REGULAR",
// 		"concat(p.amc_code,product_code)": "D04",
// 		"customeriin": null,
// 		"percentage": "19.07",
// 		"iin_exists_or_not": "no"
// 	}],
// 	"count": 30,
// 	"success": "1"
// }