export default {
  icDashboard: require('../assets/Images/BottomTab/ic_home_dashboard.png'),
  icDashboard_Active: require('../assets/Images/BottomTab/Dashboard-Active.png'),
  icNetworth: require('../assets/Images/BottomTab/ic_home_networth.png'),
  icNetworth_Active: require('../assets/Images/BottomTab/Networth-Active.png'),
  icGoals: require('../assets/Images/BottomTab/ic_home_goals.png'),
  icAlerts: require('../assets/Images/Navbar/nav_notification.png'),
  icGoals_Active: require('../assets/Images/BottomTab/Assets-Active.png'),
  icBuySell: require('../assets/Images/BottomTab/ic_home_buy_sell.png'),
  icBuySell_Active: require('../assets/Images/BottomTab/Mutual-Funds-Active.png'),
  icReadings: require('../assets/Images/BottomTab/ic_home_readings.png'),
  icReadings_Active: require('../assets/Images/BottomTab/Readings-Active.png'),
  ic_payoutalerts: require('../assets/Images/Drawer/nav_payoutalerts.png'),
  ic_termsnconditions: require('../assets/Images/Drawer/nav_termscond.png'),
  ic_calculator: require('../assets/Images/Drawer/nav_calculator.png'),
  ic_changepassword: require('../assets/Images/Drawer/nav_change_pwd.png'),
  ic_demo: require('../assets/Images/Drawer/nav_demo.png'),
  ic_chatwithadvisor: require('../assets/Images/Drawer/ic_home_readings.png'),
  ic_logout: require('../assets/Images/Drawer/nav_logout.png'),
  ic_notifications: require('../assets/Images/Drawer/nav_notification.png'),
  ic_rateus: require('../assets/Images/Drawer/nav_rateus.png'),
  ic_mypost: require('../assets/Images/Drawer/nav_mypost.png'),
  ic_dataentry: require('../assets/Images/Drawer/nav_dataentry.png'),
  ic_sample: require('../assets/Images/Drawer/ic_sample.png'),
  ic_profile: require('../assets/Images/Drawer/nav_profile.png'),
  ic_referus: require('../assets/Images/Drawer/nav_referus.png'),
  ic_share: require('../assets/Images/Drawer/nav_share.png'),
  ic_subscription: require('../assets/Images/Drawer/nav_subscription.png'),
  ic_profilegeneric: require('../assets/Images/Drawer/profile_pic_generic.png'),
  ic_privacypolicy: require('../assets/Images/Drawer/nav_privacypolicy.png'),
  ic_backbutton: require('../assets/Images/back-arrow-96.png'),
  ic_anotherback: require('../assets/Images/arrow-back-outline.png'),
  ic_chevronback: require('../assets/Images/Drawer/chevron-left.png'),
  ic_menuham: require('../assets/Images/Navbar/hamberger-menu.png'),
  ic_onboarding1: require('../assets/Images/Onboarding/scr1.png'),
  ic_onboarding2: require('../assets/Images/Onboarding/scr2.png'),
  ic_onboarding3: require('../assets/Images/Onboarding/scr3.png'),
  ic_up: require('../assets/up.png'),
  ic_down: require('../assets/down.png'),
  ic_doughnut: require('../assets/doughnut.png'),
  ic_assetpie: require('../assets/pie-chart.png'),
  ic_chart: require('../assets/ic_chart.png'),
  ic_list: require('../assets/list.png'),
  ic_banner: require('../assets/banner.jpg'),
  ic_banner1: require('../assets/greenbanner.png'),
  ic_goals: require('../assets/goals.png'),
  ic_goals2: require('../assets/goals2.png'),
  ic_arrowright: require('../assets/Arrow-right-512.png'),
  ic_market: require('../assets/Stock-Market.png'),
  ic_investmore: require('../assets/Buy-icon.png'),
  ic_redeem: require('../assets/Redeem-icon.png'),
  ic_close: require('../assets/close.png'),
  ic_info: require('../assets/info.png'),
  //Mutual Funds Logos
  ic_aditya_birla_mutual_fund: require('../assets/FundHouses/aditya-birla-mf-logo.png'),
  ic_axis_mutual_fund: require('../assets/FundHouses/axis_mutual_fund.png'),
  ic_bnp_paribhas: require('../assets/FundHouses/BNP-Paribas-Mutual-Fund.png'),
  ic_dsp: require('../assets/FundHouses/dsp-mutal-fund.png'),
  ic_icici: require('../assets/FundHouses/ICICI-Prudential-Mutual-Fund.png'),
  ic_kotak: require('../assets/FundHouses/Kotak-Mahindra-Mutual-Fund.png'),
  ic_LANDT: require('../assets/FundHouses/L&T-Mutual-Fund.png'),
  ic_SBI: require('../assets/FundHouses/SBI-Mutual-Fund.png'),
  ic_Nippon: require('../assets/FundHouses/Nippon-India-Mutual-Fund.png'),
  ic_Motilal: require('../assets/FundHouses/motilal_oswal.png'),
};



